name: .NET CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: List directory contents
        run: dir

      - name: Read configuration from JSON file (PowerShell)
        id: read_config
        shell: pwsh
        run: |
          # Read the JSON config file
          $config = Get-Content -Raw -Path "dotnet-config.json" | ConvertFrom-Json

          # Extract values from the JSON config
          $env:PUBLISH_WEB_PROJECTS = $config.publishWebProjects
          $env:PROJECTS = $config.projects
          $env:CUSTOM = $config.custom
          $env:ARGUMENTS = $config.arguments
          $env:PUBLISH_TEST_RESULTS = $config.publishTestResults

      - name: Restore dependencies
        run: |
          dotnet restore MyDotnetApp.sln `
            --publishWebProjects $env:PUBLISH_WEB_PROJECTS `
            --projects $env:PROJECTS `
            --custom $env:CUSTOM `
            --arguments $env:ARGUMENTS `
            --publishTestResults $env:PUBLISH_TEST_RESULTS

      - name: Build the project
        run: dotnet build MyDotnetApp.sln --configuration Release

      - name: Run the application
        run: dotnet run --project MyDotnetApp\MyDotnetApp.csproj
