name: .NET CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: List directory contents
        run: dir  # This helps you verify the directory structure

      - name: Read configuration from JSON file (PowerShell)
        id: read_config
        shell: pwsh
        run: |
          # Read the JSON config file
          $config = Get-Content -Raw -Path "dotnet-config.json" | ConvertFrom-Json

          # Set the values as environment variables for the entire job
          echo "CUSTOM=$($config.custom)" >> $env:GITHUB_ENV
          echo "ARGUMENTS=$($config.arguments)" >> $env:GITHUB_ENV
          echo "TEST_RUN_TITLE=$($config.testRunTitle)" >> $env:GITHUB_ENV
          echo "MODIFY_OUTPUT_PATH=$($config.modifyOutputPath)" >> $env:GITHUB_ENV
          echo "SELECT_OR_CONFIG=$($config.selectOrConfig)" >> $env:GITHUB_ENV
          echo "FEED_RESTORE=$($config.feedRestore)" >> $env:GITHUB_ENV
          echo "INCLUDE_NUGET_ORG=$($config.includeNuGetOrg)" >> $env:GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "CUSTOM = $CUSTOM"
          echo "ARGUMENTS = $ARGUMENTS"
          echo "TEST_RUN_TITLE = $TEST_RUN_TITLE"
          echo "MODIFY_OUTPUT_PATH = $MODIFY_OUTPUT_PATH"
          echo "SELECT_OR_CONFIG = $SELECT_OR_CONFIG"
          echo "FEED_RESTORE = $FEED_RESTORE"
          echo "INCLUDE_NUGET_ORG = $INCLUDE_NUGET_ORG"

      - name: Build the project
        run: |
          echo "Building the project with the following parameters:"
          echo "Custom: $CUSTOM"
          echo "Arguments: $ARGUMENTS"
          echo "ModifyOutputPath: $MODIFY_OUTPUT_PATH"
          echo "SelectOrConfig: $SELECT_OR_CONFIG"
          echo "FeedRestore: $FEED_RESTORE"
          echo "IncludeNuGetOrg: $INCLUDE_NUGET_ORG"

          dotnet build MyDotnetApp.sln --configuration Release `
            -p:Custom="$CUSTOM" `
            -p:Arguments="$ARGUMENTS" `
            -p:ModifyOutputPath="$MODIFY_OUTPUT_PATH" `
            -p:SelectOrConfig="$SELECT_OR_CONFIG" `
            -p:FeedRestore="$FEED_RESTORE" `
            -p:IncludeNuGetOrg="$INCLUDE_NUGET_ORG"

      - name: Run the application
        run: dotnet run --project MyDotnetApp\MyDotnetApp.csproj
