name: .NET CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: List directory contents
        run: dir

      - name: Read configuration from JSON file (PowerShell)
        id: read_config
        shell: pwsh
        run: |
          # Read the JSON config file
          $config = Get-Content -Raw -Path "dotnet-config.json" | ConvertFrom-Json

          # Extract values from the JSON config and set them as environment variables
          $env:CUSTOM = $config.custom
          $env:ARGUMENTS = $config.arguments
          $env:TEST_RUN_TITLE = $config.testRunTitle
          $env:MODIFY_OUTPUT_PATH = $config.modifyOutputPath
          $env:SELECT_OR_CONFIG = $config.selectOrConfig
          $env:FEED_RESTORE = $config.feedRestore
          $env:INCLUDE_NUGET_ORG = $config.includeNuGetOrg

      - name: Restore dependencies
        run: |
          dotnet restore MyDotnetApp.sln `
            -p:Custom=$env:CUSTOM `
            -p:Arguments=$env:ARGUMENTS `
            -p:ModifyOutputPath=$env:MODIFY_OUTPUT_PATH `
            -p:SelectOrConfig=$env:SELECT_OR_CONFIG `
            -p:FeedRestore=$env:FEED_RESTORE `
            -p:IncludeNuGetOrg=$env:INCLUDE_NUGET_ORG

      - name: Build the project
        run: |
          dotnet build MyDotnetApp.sln --configuration Release `
            -p:Custom=$env:CUSTOM `
            -p:Arguments=$env:ARGUMENTS `
            -p:ModifyOutputPath=$env:MODIFY_OUTPUT_PATH `
            -p:SelectOrConfig=$env:SELECT_OR_CONFIG `
            -p:FeedRestore=$env:FEED_RESTORE `
            -p:IncludeNuGetOrg=$env:INCLUDE_NUGET_ORG

      - name: Publish the project
        run: |
          dotnet publish MyDotnetApp.sln --configuration Release `
            -p:TestRunTitle=$env:TEST_RUN_TITLE `
            -p:ModifyOutputPath=$env:MODIFY_OUTPUT_PATH `
            -p:SelectOrConfig=$env:SELECT_OR_CONFIG `
            -p:FeedRestore=$env:FEED_RESTORE `
            -p:IncludeNuGetOrg=$env:INCLUDE_NUGET_ORG

      - name: Run the application
        run: dotnet run --project MyDotnetApp\MyDotnetApp.csproj
