name: .NET Restore and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  restore-and-build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'

    # Step 3: Restore dependencies for the project or solution
    - name: Restore dependencies
      run: |
        if [ -f MySolution.sln ]; then
          echo "Restoring solution MySolution.sln"
          dotnet restore MySolution.sln
        elif [ -f MyProject.csproj ]; then
          echo "Restoring project MyProject.csproj"
          dotnet restore MyProject.csproj
        else
          echo "No .sln or .csproj file found in the directory."
          exit 1
        fi

    # Display the .NET version
    - name: Display .NET version
      run: dotnet --version

    # Step 4: Build the project or solution
    - name: Build project
      run: |
        if [ -f MySolution.sln ]; then
          dotnet build MySolution.sln
        elif [ -f MyProject.csproj ]; then
          dotnet build MyProject.csproj
        else
          echo "No .sln or .csproj file found in the directory."
          exit 1
        fi

    # Step 5: Run tests
    - name: Run unit tests
      run: |
        if [ -f MySolution.sln ]; then
          dotnet test MySolution.sln
        elif [ -f MyProject.csproj ]; then
          dotnet test MyProject.csproj
        else
          echo "No .sln or .csproj file found in the directory."
          exit 1
        fi
